//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesseracts.DMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTag
    {
        public DocumentTag()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
    }
}
